name: Build and Test Panoptes Plugin

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev libssl-dev build-essential git

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for pbr versioning

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Downgrade pip and setuptools
        run: |
          python3 -m pip install --upgrade "pip<24.1"
          python3 -m pip install "setuptools<58.0.0"

      - name: Install build dependencies
        run: |
          python3 -m pip install pbr wheel

      - name: Install Panoptes with relaxed dependencies
        run: |
          # Temporarily modify requirements to allow newer Celery
          sed -i 's/celery==4.4.7/celery>=4.4.7/' setup.cfg || true
          pip install -e .

      - name: Run tests
        run: |
          python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"