name: Run Malicious Panoptes Plugin

on: [push]

jobs:
  run-malicious-plugin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requirements
      run: pip install .

    - name: Run malicious plugin
      run: |
        python3 -c "
from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP
PluginPollingEvilSNMP().run({})
        "
