name: Run Malicious Panoptes Plugin

on: [push]

jobs:
  run-malicious-plugin:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Downgrade pip (avoid pip 24+ issues)
        run: pip install "pip<24.1"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1 libssl-dev build-essential

      - name: Install Panoptes (patched)
        run: pip install .

      - name: Run malicious plugin
        run: |
          python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"
