name: Build and Test Panoptes Plugin

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for pbr versioning

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip python3-dev \
            libssl-dev build-essential \
            libsnmp-dev snmp-mibs-downloader

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Configure environment
        run: |
          # Downgrade pip to version that accepts older metadata formats
          python3 -m pip install --upgrade "pip<24.1"
          # Install compatible setuptools version
          python3 -m pip install "setuptools<58.0.0"

      - name: Install Celery 4.4.7 first (with relaxed checks)
        run: |
          python3 -m pip install \
            --no-deps \
            --ignore-requires-python \
            "celery==4.4.7"

      - name: Install remaining dependencies
        run: |
          python3 -m pip install pbr wheel

      - name: Install Panoptes in editable mode
        run: |
          python3 -m pip install -e . --no-deps
          python3 -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"