name: Build and Test

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - run: apt-get update && apt-get install -y python3-pip libssl1.1 libssl-dev build-essential
      - run: pip3 install "pip<24.1"
      - run: pip3 install .
      - run: python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"
