name: Build and Test Panoptes Plugin

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Git (v2.18+)
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install -y git

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for pbr versioning
          submodules: recursive  # Now works with proper Git version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev libssl-dev build-essential

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pbr wheel setuptools

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run tests
        run: |
          python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"