name: Build and Test Panoptes Plugin

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip python3-dev \
            libssl-dev build-essential \
            libsnmp-dev snmp-mibs-downloader

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Configure environment
        run: |
          # Use older OpenSSL compatible with Net-SNMP 5.7.3
          export CFLAGS="-Wno-error=deprecated-declarations"
          export CPPFLAGS="-Wno-error=deprecated-declarations"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install wheel setuptools pbr

      - name: Patch Net-SNMP source
        run: |
          # Fix OpenSSL compatibility issues
          find . -name 'keytools.c' -exec sed -i \
            -e 's/EVP_MD_CTX_cleanup/EVP_MD_CTX_reset/g' \
            -e 's/malloc(sizeof(\*ctx))/EVP_MD_CTX_new()/g' \
            {} \;

      - name: Install Panoptes
        run: |
          pip install --ignore-installed PyOpenSSL
          pip install -e . --verbose

      - name: Run tests
        run: |
          python3 -c "from yahoo_panoptes.plugins.polling.plugin_polling_evil_snmp import PluginPollingEvilSNMP; PluginPollingEvilSNMP().run({})"